### ISSUE TITLE
Solve error CS0118: 'Themer'

### ISSUE THREAD

**Issue by CronexTR** [DestroyerDarkNess/BF4-External#1]
BF4-External-main\BF4-External-main\ExternalSharp\Program.cs(60,34,60,40): error CS0118: 'Themer'

**Comment by CronexTR** [comment]
BF4-External-main\BF4-External-main\ExternalSharp\Program.cs(180,37,180,42): error CS0103: 'Theme'

**Comment by DestroyerDarkNess** [comment]
![image](https://github.com/DestroyerDarkNess/BF4-External/assets/32405118/1e841dc5-466c-4382-8200-6fc4bdb73e16)

**Download :** [https://github.com/arshx86/Themer/releases/tag/v2.0](ThemeReleases)

![image](https://github.com/DestroyerDarkNess/BF4-External/assets/32405118/741942e9-be33-43f1-b7c1-1ebb4b35602f)

**Add DLL to Project :**  

![image](https://github.com/DestroyerDarkNess/BF4-External/assets/32405118/4a0b51d1-8d26-453a-97f5-ac2ac2a75402)

![image](https://github.com/DestroyerDarkNess/BF4-External/assets/32405118/b0347b7f-4a42-4bdb-aa3f-efc74a1d3c77)

**Then press accept and that's it.**

**Comment by DestroyerDarkNess** [comment]
Solved.
